CURSOR_BASE_COST = 10
WORKER_BASE_COST = 50
FARM_BASE_COST = 200
FACTORY_BASE_COST = 50

CURSOR_EFFECT = 1
WORKER_EFFECT = 1
FARM_EFFECT = 5
FACTORY_EFFECT = 100

CPS_MULTIPLIER = 1.15
CLICK_POWER = 1

UI_UPDATE_FREQUENCY = 50
SAVE_FREQUENCY = 10000
